### PR TITLE
Fix example after f8846218b api change

### PR DESCRIPTION
**Pull request by a86c6f7964**

### CODE REVIEW

**Comment by talevy** [comment]
thank you for this fix!

**Comment by talevy** [comment]
@a86c6f7964 can you please sign the CLA? https://github.com/elasticsearch/logstash/blob/master/CONTRIBUTING.md#contribution-steps

then I'll be able to go ahead and merge :smile:!

**Comment by a86c6f7964** [comment]
Okay I signed it.

**Comment by talevy** [comment]
thanks @a86c6f7964!

**Pull request closed without merging**
