### PR TITLE
Make base64 encoding optional

### PR DESCRIPTION
**Pull request by pascalgulikers**
Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by pascalgulikers** [comment]
Signed the CLA but it's not getting updated here

**Comment by pascalgulikers** [comment]
Can you please merge this PR? It's just a minor change and it will help us a lot! Thanks in advance :)

**Comment by pascalgulikers** [comment]
@robbavey @roaksoax Best wishes! Can you please merge this PR?

**Comment by andsel** [comment]
Hi @pascalgulikers 
I've force pushed one commit to this PR and, for a reason I don't know, it closed this PR.
I've moved the work to #39 and added you as Co-author to preserve your contribution.
Sorry for that, I think it's due to be on `main` branch instead of a separate PR branch.

**Comment by andsel** [comment]
Hi @pascalgulikers thank's for your contribution :clap:  this work has been published with https://rubygems.org/gems/logstash-codec-avro/versions/3.4.0-java

**Pull request closed without merging**
