### PR TITLE
[WIP] Add option to encode as binary RubyString instead of base64

### PR DESCRIPTION
**Pull request by original-brownbear**
Use setting `encode_as_base64 => false` to test :)

### CODE REVIEW

**Comment by Rubyan** [comment]
@original-brownbear good job! I'm seeing consistent messages during the json / avro / kafka route.

**Comment by original-brownbear** [comment]
@Rubyan nice, will see to it that this gets fixed up (need to improve the docs now) and merged + published shortly then :)

**Comment by haoyu0624** [comment]
Hello, why did I use your file or not? I am looking forward to your reply.
This is an error message
Exception in thread "main" org.apache.avro.AvroRuntimeException: Malformed data. Length is negative: -1552376

**Comment by original-brownbear** [comment]
@andrewvc assigning you here, just because I need some feedback from you on this (after the holidays). This is done already, but we need to think about the BwC and documentation required for this change. Will add details soon.

**Comment by Rubyan** [comment]
Any update on a possible merge?

**Comment by juvlarN** [comment]
@original-brownbear any chance to get this merged soonish?

**Comment by rbkasat** [comment]
Can someone merge this? We need this asap.

**Comment by original-brownbear** [comment]
@jsvd FYI :)

**Comment by Rubyan** [comment]
@original-brownbear The tests are all good, there are no conflicts, can you merge this?

**Comment by original-brownbear** [comment]
@jsvd pong :)

**Comment by guillaume7** [comment]
Can you please make this merge work? Thank you!

**Comment by petericebear** [comment]
I have a customer waiting for this to merge. Can we get a timing on the release for this?

**Pull request closed without merging**
