### PR TITLE
Send event and encoded data as a result of Avro encoding

### PR DESCRIPTION
**Pull request by i-maravic**

### CODE REVIEW

**Comment by talevy** [comment]
sweet! sorry for the late response. I would be happy to merge this in.

can you please sign the CLA? https://github.com/elasticsearch/logstash/blob/master/CONTRIBUTING.md#contribution-steps

**Comment by oruen** [comment]
I believe I can't use logstash-codec-avro with logstash-kafka-output because it's missing `event` object in `on_event` callbacks. Should send PR (equal to this one), sign the CLA and the it will get merged? /cc @talevy

**Comment by oruen** [comment]
Anyway I've made https://github.com/logstash-plugins/logstash-codec-avro/pull/4

**Comment by talevy** [comment]
Closing in favor of #4.

**Pull request closed without merging**
