### PR TITLE
Use byte array for data passed in on_event callback. #5

### PR DESCRIPTION
**Pull request by oruen**
Convert data to and from byte array #5

This patch introduce jruby-specific methods and breaks compatibility with MRI. I'm not sure about this approach so feedback is appreciated.

### CODE REVIEW

**Comment by talevy** [comment]
@oruen which plugins are you using this update to the codec with?

**Comment by oruen** [comment]
@talevy I'm using logstash-input-file, logstash-filter-mutate, logstash-codec-avro and logstash-output-kafka.

Here is my config file:
```
input {
  file {
    path => "/var/log/nginx/playback-access.log"
  }
}

filter {
  mutate {
    rename => ["@timestamp", "timestamp"]
    add_field => {
      "body" => "%{message}"
      "service" => "playback-logstash"
    }
    remove_field => ["message", "path", "@version"]
  }
  mutate {
    convert => ["timestamp", "integer"]
  }
}

output {
  kafka {
    codec => avro {
      schema_uri => "/etc/virool/avro/playbacks.avsc"
    }
    broker_list => "192.168.3.71:6667,192.168.3.73:6667" # string (optional), default: "localhost:9092"
    topic_id => "playbacks" # string (optional), default: "test"
    compression_codec => "snappy" # string (optional), one of ["none", "gzip", "snappy"], default: "none"
    compressed_topics => "" # string (optional), default: ""
    request_required_acks => 0 # number (optional), one of [-1, 0, 1], default: 0
    request_timeout_ms => 10000 # number (optional) default: 10000
    producer_type => "sync" # string (optional), one of ["sync", "async"] default => 'sync'
    message_send_max_retries => 3 # number (optional) default: 3
    retry_backoff_ms => 100 # number (optional) default: 100
    topic_metadata_refresh_interval_ms => 600000 # number (optional) default: 600 * 1000
    send_buffer_bytes => 1024100 # number (optional) default: 100 * 1024
    client_id => "playback-192.168.3.31" # string (optional) default: ""
    serializer_class => "kafka.serializer.DefaultEncoder"
    key_serializer_class => "kafka.serializer.DefaultEncoder"
  }
}
```

**Comment by purbon** [comment]
please jenkins, test this.

**Comment by codenamelxl** [comment]
Any progress on this? I have same problem, hoping we can merge this soon. Thank you.

**Comment by suyograo** [comment]
Fixed in https://github.com/logstash-plugins/logstash-codec-avro/pull/24

**Pull request closed without merging**
